config/routes.rb
Rails.application.routes.draw do
  resources :app_functionalities
  resources :articles
  devise_for :app_users, controllers: {
    sessions: 'app_users/sessions',
    passwords: 'app_users/passwords',
    registrations: 'app_users/registrations',
    confirmations: 'app_users/confirmations',
    unlocks: 'app_users/unlocks',
    mailer: 'app_users/mailer',
  }
  resources :users
  root 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>Copyrights by <a href="#"></a> usama</small>
  </footer>
  <nav>
    <li><%= link_to "Buyers", users_path  %></li>
  </nav>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "My Project", root_path, class: 'navbar-brand', id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "Buyers", users_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Article", articles_path , class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Controls", app_functionalities_path , class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>