config/routes.rb
Rails.application.routes.draw do
  resources :app_functionalities
  resources :articles
  devise_for :app_users, controllers: {
    sessions: 'app_users/sessions',
    passwords: 'app_users/passwords',
    registrations: 'app_users/registrations',
    confirmations: 'app_users/confirmations',
    unlocks: 'app_users/unlocks',
    mailer: 'app_users/mailer',
  }
  resources :users
  root 'welcome#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/app_functionality.rb
class AppFunctionality < ApplicationRecord
end

app/controllers/app_functionalities_controller.rb
class AppFunctionalitiesController < ApplicationController
  before_action :set_app_functionality, only: %i[ show edit update destroy ]

  # GET /app_functionalities or /app_functionalities.json
  def index
    @app_functionalities = AppFunctionality.all
  end

  # GET /app_functionalities/1 or /app_functionalities/1.json
  def show
  end

  # GET /app_functionalities/new
  def new
    @app_functionality = AppFunctionality.new
  end

  # GET /app_functionalities/1/edit
  def edit
  end

  # POST /app_functionalities or /app_functionalities.json
  def create
    @app_functionality = AppFunctionality.new(app_functionality_params)

    respond_to do |format|
      if @app_functionality.save
        format.html { redirect_to app_functionality_url(@app_functionality), notice: "App functionality was successfully created." }
        format.json { render :show, status: :created, location: @app_functionality }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @app_functionality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_functionalities/1 or /app_functionalities/1.json
  def update
    respond_to do |format|
      if @app_functionality.update(app_functionality_params)
        format.html { redirect_to app_functionality_url(@app_functionality), notice: "App functionality was successfully updated." }
        format.json { render :show, status: :ok, location: @app_functionality }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @app_functionality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_functionalities/1 or /app_functionalities/1.json
  def destroy
    @app_functionality.destroy

    respond_to do |format|
      format.html { redirect_to app_functionalities_url, notice: "App functionality was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_functionality
      @app_functionality = AppFunctionality.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def app_functionality_params
      params.require(:app_functionality).permit(:app_version, :app_package, :is_locked, :app_image, :app_message)
    end
end

app/helpers/app_functionalities_helper.rb
module AppFunctionalitiesHelper
end

app/views/app_functionalities/_form.html.erb
<%= form_with(model: app_functionality) do |form| %>
  <% if app_functionality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app_functionality.errors.count, "error") %> prohibited this app_functionality from being saved:</h2>

      <ul>
        <% app_functionality.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :app_version %>
    <%= form.text_field :app_version %>
  </div>

  <div class="field">
    <%= form.label :app_package %>
    <%= form.text_field :app_package %>
  </div>  <div class="field">
    <%= form.label :app_image %>
    <%= form.text_field :app_image %>
  </div>  <div class="field">
    <%= form.label :app_message %>
    <%= form.text_field :app_message %>
  </div>

  <div class="field">
    <%= form.label :is_locked %>
    <%= form.check_box :is_locked %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/app_functionalities/edit.html.erb
<h1>Editing App Functionality</h1>

<%= render 'form', app_functionality: @app_functionality %>

<%= link_to 'Show', @app_functionality %> |
<%= link_to 'Back', app_functionalities_path %>

app/views/app_functionalities/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-lg-12 mx-md-auto"><h1>App Functionalities</h1>

      <table class="table table-bordered">
        <thead>
        <tr>
          <th>App version</th>
          <th>App package</th>
          <th>App message</th>
          <th>App image</th>
          <th>Is locked</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @app_functionalities.each do |app_functionality| %>
          <tr>
            <td><%= app_functionality.app_version %></td>
            <td><%= app_functionality.app_package %></td>
            <td><%= app_functionality.app_message %></td>
            <td><%= app_functionality.app_image %></td>
            <td><%= app_functionality.is_locked %></td>
            <td><%= link_to 'Show', app_functionality %></td>
            <td><%= link_to 'Edit', edit_app_functionality_path(app_functionality) %></td>
            <td><%= link_to 'Destroy', app_functionality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New App Functionality', new_app_functionality_path %>

    </div>
  </div>
</div>

app/views/app_functionalities/new.html.erb
<h1>New App Functionality</h1>

<%= render 'form', app_functionality: @app_functionality %>

<%= link_to 'Back', app_functionalities_path %>

app/views/app_functionalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>App version:</strong>
  <%= @app_functionality.app_version %>
</p>

<p>
  <strong>App package:</strong>
  <%= @app_functionality.app_package %>
</p>

<p>
  <strong>Is locked:</strong>
  <%= @app_functionality.is_locked %>
</p>

<%= link_to 'Edit', edit_app_functionality_path(@app_functionality) %> |
<%= link_to 'Back', app_functionalities_path %>